; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
monitor_echo = true
monitor_eol = CRLF
build_src_filter =
  +<main.cpp>

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1

lib_deps =
  jgromes/RadioLib
  olikraus/U8g2
  https://github.com/xreef/LoRa_E32_Series_Library.git

[env:e79-esp32-bridge]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_EBYTE_E79_CC1352P
  -DRADIO_PROGRAM=AT_COMMANDS

[env:cc1101-v1-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_CC1101_V1_433
  -DRADIO_PROGRAM=AT_COMMANDS

[env:cc1101-v2-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_CC1101_V2_868
  -DRADIO_PROGRAM=AT_COMMANDS

[env:ra01h-sx1276-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_RA01H_SX1276
  -DRADIO_PROGRAM=AT_COMMANDS

[env:ra01sh-sx1262-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_RA01SH_SX1262
  -DRADIO_PROGRAM=AT_COMMANDS

[env:ra02-sx1278-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_RA02_SX1278
  -DRADIO_PROGRAM=AT_COMMANDS

[env:e28-sx1280-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_E28_SX1280
  -DRADIO_PROGRAM=AT_COMMANDS

[env:hc12-power-test]
extends = env:esp32-c3-devkitc-02
build_flags =
  ${env:esp32-c3-devkitc-02.build_flags}
  -DRADIO_MODULE=RADIO_HC12
  -DRADIO_PROGRAM=AT_COMMANDS
